### ISSUE TITLE
Test  KeyPhrase Extraction model against Top25 Mappings from MITRE CWE

### ISSUE THREAD

**Issue by Crashedmind** [CyberSecAI/CWEMap#13]
https://github.com/CyberSecAI/top25_cwe_assign_compare

- [x] get keyphrases https://github.com/CyberSecAI/cve_info
- [x] Get content from reference links 
- [ ] assign CWE(s) blind i.e. without knowing existing assigned CWEs
- [ ] Check if the currently assigned CWEs are correct (with a confidence). 
-  CVE description + References refined.md + key_phrases cve_info: create a CVE info file 
- assigned CWE(s) + CWE description(s) + known good examples for CWE

- [ ] Arbitrate and Assign the correct CWE with rationale

https://github.com/orgs/CyberSecAI/projects/2/views/1?pane=issue&itemId=85356716&issue=CyberSecAI%7CCWEMap%7C30

The Top25 mappings should be split into 2 sets:
1. for RAG use
2. for testing against

 KeyPhrase Extraction for all 6945 CVEs

- [x]  Check against original
- [x]  fill gaps
- [x]  check no "denial" or "exec" in rootcause or weakness
- [x]  check against weakness_description
- [x]  add description back in
- [x] make tags lowercase e.g. WEAKNESS
- [x] use "" instead of null or blank for testing model

Evaluate
- [x]  Convert to json
- [ ]  Check Impact against previous analysis
- [ ] Check weakness against Hold out sample of Top25 mappings
- [ ]  Use GCP Evaluate or Side-by-Side to eval
- [ ] Evaluate against Other models
- [x] Apply to CISA KEV ~1.5K CVEs
